[mainConfig]
appName = "GoNexus"
host = "127.0.0.1"
port = 8080

[emailConfig]
authcode = "qjcmbgqledkbbjaj"
email = "1746502977@qq.com"

[redisConfig]
host = "140.143.239.3"
port = 16379
password = "admin"
db = 0

[mysqlConfig]
host = "140.143.239.3"
port = 13306
user = "root"
password = "123456"
databaseName = "GoNexus"
charset =  "utf8mb4"

[jwtConfig]
expireDay= 8760
issuer= "DreamTower"
subject= "GoNexus"
secret= "GoNexus"

[rabbitmqConfig]
host= "140.143.239.3"
port= 5672
username= "admin"
password= "admin"
vhost= "/"

[ragModelConfig]
embeddingModel= "text-embedding-v4"
chatModelName = "qwen-plus"
baseUrl= "https://dashscope.aliyuncs.com/compatible-mode/v1"
dimension= 1024

[deepseekConfig]


[qwenConfig]

